Bonus Problem (HOSVD)

In [40]:
import numpy as np
np.set_printoptions(precision = 3)
def Hilbert_tensor(n):
    a = np.zeros((n,n,n))
    args = np.arange(n)
    print args
    for i in args:
        for j in args:
            for k in args:
                #a[i,j,k] = 1./(i + j + k + 1)
                a[i,j,k]= i*j*k
    return a


N = 3
H = Hilbert_tensor(n)
print H
print H.reshape(9,3,order = "C")

[0 1 2]
[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  1.  2.]
  [ 0.  2.  4.]]

 [[ 0.  0.  0.]
  [ 0.  2.  4.]
  [ 0.  4.  8.]]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  1.  2.]
 [ 0.  2.  4.]
 [ 0.  0.  0.]
 [ 0.  2.  4.]
 [ 0.  4.  8.]]


Transforming 3D-tensor to matrix (n-mode flattening)

In [ ]:
def flattening(X,n):
    #n - mode
    I = X.shape
    A = np.zeros((I[n], I[(n + 1) % 3] * I[(n + 2) % 3]))
    for i1 in xrange(I[0]):
        for i2 in xrange(I[1]):
            for i3 in xrange(I[2]):
                J = np.ones(3,)
                for k in xrange(3):
                    for m in xrange(k):
                        if m != n:
                            J[k] *= I[m]
                    
                j = i1*J[0]*(n != 0) + i2*J[1]*(n != 1) + i3*J[2]*(n != 2) 
                i = 0
                if n == 0:
                    i = i1
                    elif n == 1:
                        i = i2
                        else i = i3
                A[i,j] = X[i1,i2,i3]
    return A